#!/bin/sh

# Uncomment the following two lines for normal desktop:
# unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

# vncconfig -iconic &
autocutsel -fork &
x-terminal-emulator -geometry 80x24+10+10 &

gnome-panel &
gnome-settings-daemon &
metacity &

xsetroot -solid grey &
feh --bg-scale http://www.planwallpaper.com/static/images/i-should-buy-a-boat.jpg &
