---
- name: Add /etc/hosts for trystack1
  hosts: beijing
  remote_user: ubuntu
  gather_facts: no
  become: yes

  roles:
    - {
        role: cloud-inventory,
        group_hosts: "{{ trystack1 }}"
      }

- name: Add /etc/hosts for trystack2
  hosts: trystack2
  remote_user: centos
  gather_facts: no
  become: yes

  roles:
    - {
        role: cloud-inventory,
        group_hosts: "{{ trystack2 }}"
      }

- name: Setup beijing
  hosts: beijing
  remote_user: ubuntu
  gather_facts: no
  become: yes
  become_method: sudo

  roles:
    - {
        role: ubuntu-ftpd,
        anon_root: /home/ubuntu
      }
    - {
        role: ubuntu-ddclient,
        var_domain: open
      }
    - ubuntu-k8s
    - ubuntu-bt
    - {
        role: ubuntu-vnc,
        password4vnc: s3cr3t
      }
...
